// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace BOTB_Scraper
{
    public partial class MLModelNew
    {
        /// <summary>
        /// model input class for MLModelNew.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"CompetitionRef")]
            public string CompetitionRef { get; set; }

            [ColumnName(@"JudgesSelectionX")]
            public float JudgesSelectionX { get; set; }

            [ColumnName(@"JudgesSelectionY")]
            public float JudgesSelectionY { get; set; }

            [ColumnName(@"LeftPlayerLeftEyeX")]
            public float LeftPlayerLeftEyeX { get; set; }

            [ColumnName(@"LeftPlayerLeftEyeY")]
            public float LeftPlayerLeftEyeY { get; set; }

            [ColumnName(@"LeftPlayerRightEyeX")]
            public float LeftPlayerRightEyeX { get; set; }

            [ColumnName(@"LeftPlayerRightEyeY")]
            public float LeftPlayerRightEyeY { get; set; }

            [ColumnName(@"RightPlayerLeftEyeX")]
            public float RightPlayerLeftEyeX { get; set; }

            [ColumnName(@"RightPlayerLeftEyeY")]
            public float RightPlayerLeftEyeY { get; set; }

            [ColumnName(@"RightPlayerRightEyeX")]
            public float RightPlayerRightEyeX { get; set; }

            [ColumnName(@"RightPlayerRightEyeY")]
            public float RightPlayerRightEyeY { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModelNew.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModelNew.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
